### ISSUE TITLE
Calm winds + Annotation 

### ISSUE THREAD

**Issue by jmclaren17** [davidcarslaw/openair#261] opened 2021-06-16 09:51 UTC
Hi David, 

I think the issue with calm winds has previously been discussed that sometimes calms are defined as something other than the default in openair i.e. 0.  As such I have been able to override that by using the annotate feature which was a good workaround, however I have recently updated openair and now experiencing an issue. 

The annotate feature now plots what I want it to for mean and calm, each line ends with "= X.XXXX" and "= X%" respectively for mean and calm on the plot.  (see screenshot). 

Is there a way the user can define what calms are without impacting the mean?  Alternatively, could the error I identified be rectified so I can continue to use the workaround. 

Thanks!

![image](https://user-images.githubusercontent.com/28139355/122197947-9bd56c80-ce90-11eb-8ce5-9c2a2ab34db7.png)

**Comment by jack-davison** [comment] 2023-02-09 09:32
Closing as a duplicate of https://github.com/davidcarslaw/openair/issues/221. Feel free to continue the conversation there! This could clearly be a useful addition so we'll look into it.

**Closed by jack-davison** 2023-02-09 09:32 UTC
Labels: duplicate
