### ISSUE TITLE
Suppress year on calendar plot

### ISSUE THREAD

**Issue by rafaelrsss** [davidcarslaw/openair#190] opened 2019-02-28 18:41 UTC
Calendar plot is amazing but I usually plot a mean of 15 years and not 1 specifc year. Does anybody knows how to supress or not display the year besides the month name on the calendar?

Thanks.

**Comment by jack-davison** [comment] 2023-02-08 12:18
Closing as a duplicate of https://github.com/davidcarslaw/openair/issues/150 so do continue the conversation there. We'll look into this as it is a nice enhancement for use cases like yours!

**Closed by jack-davison** 2023-02-08 12:18 UTC
Labels: duplicate
