### ISSUE TITLE
Secondary Axis - smoothTrend analysis

### ISSUE THREAD

**Issue by jmclaren17** [davidcarslaw/openair#116] opened 2017-06-14 09:10 UTC
Dear David, 

Is there any way to plot two pollutants on separate axis using the smoothTrend function?

I would like to demonstrate the difference in the trends in NOx and NO2, I have produced this on one axis, but the NO2 trend is not really visible due to scale.

I know there are ways of plotting similar graphs using other functions such as timePlot and the normalise function.  However I do not want to lose the "deseason" option of the smoothTrend function. 

Do you or anyone have any suggestions how to:

1. Plot secondary axis in the openair package; 
2. Plot without losing the "deseason" option. 

Kind regards,
Josh

**Comment by lyggd** [comment] 2017-08-24 23:15
co-ask ! Plot secondary axis in the openair package;

**Comment by romainderain** [comment] 2018-04-11 15:45
How to draw a second ordinate axis?

**Comment by jack-davison** [comment] 2023-02-08 11:15
Closing as this is a duplicate of https://github.com/davidcarslaw/openair/issues/12, so do continue the conversation there if you're interested in secondary axes. However, broadly speaking, there's a lot of [reasons](https://blog.datawrapper.de/dualaxis/) why secondary y axes are a bad idea, and commonly there are less misleading data visualisation strategies.

If you are really keen on a secondary y axis, you could look to use `ggplot2`, although its authors also warn against using secondary axes.

``` r
library(openair)
library(tidyverse)
#> Warning: package 'ggplot2' was built under R version 4.2.2
#> Warning: package 'purrr' was built under R version 4.2.2
#> Warning: package 'dplyr' was built under R version 4.2.2
#> Warning: package 'stringr' was built under R version 4.2.2
#> Warning: package 'forcats' was built under R version 4.2.2

data <- smoothTrend(mydata, c("nox", "no2"), plot = FALSE)$data

# shift secondary pollutant to be on a similar scale
data$data <- data$data %>%
  mutate(
    conc = if_else(variable == "no2", conc * 5, conc),
    variable = case_match(variable, "no2" ~ "NO<sub>2</sub>", "nox" ~ "NO<sub>x</sub>")
  )

data$fit <- data$fit %>%
  mutate(pred = if_else(variable == "no2", pred * 5, pred),
         lower = if_else(variable == "no2", lower * 5, lower),
         upper = if_else(variable == "no2", upper * 5, upper),
         variable = case_match(variable, "no2" ~ "NO<sub>2</sub>", "nox" ~ "NO<sub>x</sub>"))

# make ggplot2
ggplot(mapping = aes(x = date)) +
  geom_point(data = data$data, aes(y = conc, color = variable)) +
  geom_line(data = data$data, aes(y = conc, color = variable)) +
  geom_line(data = data$fit, aes(y = pred, color = variable)) +
  geom_ribbon(data = data$fit,
              aes(ymax = upper, ymin = lower, fill = variable),
              alpha = .5) +
  scale_y_continuous(name = quickText("NOx (ug/m3)"), # shift secondary axis back by the same factor
                     sec.axis = sec_axis(~ . / 5, name = quickText("NO2 (ug/m3)"))) +
  theme_bw() +
  theme(legend.text = ggtext::element_markdown())
```

![](https://i.imgur.com/g5Ii5QH.png)

<sup>Created on 2023-02-08 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Closed by jack-davison** 2023-02-08 11:15 UTC
