### ISSUE TITLE
forward trajectory labels piled

### ISSUE THREAD

**Issue by manleiva** [davidcarslaw/openair#267] opened 2021-08-16 20:59 UTC
Someone can help me.

In the cluster analysis the percentage of contribution in the forward trajectory is shown at the beginning of the trajectory. This causes that they are all overlapped (piled) and it doesn't look good. How is it possible to show them at the end of the forward trajectory?.

![000-Sin título](https://user-images.githubusercontent.com/24917587/129628800-bd73ac3c-90a8-4dcb-88f3-5bf5527815c2.png)

**Comment by jack-davison** [comment] 2023-02-08 18:30
I'm closing this as a duplicate of #165. Feel free to continue the conversation at #165, as this does need looking at. Thanks!

**Closed by jack-davison** 2023-02-08 18:30 UTC
Labels: duplicate, hysplit 🌐
