### ISSUE TITLE
Calm Wind in openair

### ISSUE THREAD

**Issue by Juansalcedo494** [davidcarslaw/openair#221] opened 2020-02-18 19:16 UTC
How to put calm winds greater than 0 m / s?
I have winds less than 0.5 m / s and I want those to be calm winds

**Comment by jmclaren17** [comment] 2020-02-19 09:30
I would be interested in understanding how to do this too.  I have historically just edited the source data and annotated the calms.

**Comment by davidcarslaw** [comment] 2020-02-19 09:40
You could set the data with wind speeds <= 0.5 to zero e.g.

mydata$ws[mydata$ws <= 0.5] = 0

**Comment by Juansalcedo494** [comment] 2020-02-22 19:50
But in that case the mean would be incorrect, isn't there any other way to change calm winds?

**Comment by Juansalcedo494** [comment] 2020-02-22 19:53
But in this case the mean of calm winds would be wrong, is there no other way to change it?

**Comment by jack-davison** [comment] 2023-02-09 09:33
Reproducing comment from #261 from @jmclaren17.

> Hi David,
> 
> I think the issue with calm winds has previously been discussed that sometimes calms are defined as something other than the default in openair i.e. 0. As such I have been able to override that by using the annotate feature which was a good workaround, however I have recently updated openair and now experiencing an issue.
> 
> The annotate feature now plots what I want it to for mean and calm, each line ends with "= X.XXXX" and "= X%" respectively for mean and calm on the plot. (see screenshot).
> 
> Is there a way the user can define what calms are without impacting the mean? Alternatively, could the error I identified be rectified so I can continue to use the workaround.
> 
> Thanks!
> 
> ![image](https://user-images.githubusercontent.com/28139355/122197947-9bd56c80-ce90-11eb-8ce5-9c2a2ab34db7.png)

**Comment by jack-davison** [comment] 2023-02-10 16:26
Closing this as its a duplicate of https://github.com/davidcarslaw/openair/issues/93, where more testing/conversation has happened. Feel free to continue the conversation over there.

**Closed by jack-davison** 2023-02-10 16:26 UTC
Labels: directional 🧭
