### ISSUE TITLE
“argument ”x“ is missing, with no default” in openair package

### ISSUE THREAD

**Issue by itsabreg** [davidcarslaw/openair#152] opened 2018-05-31 06:53 UTC
I want to calculate Cluster with the 'Openair' package. I read the trajectory data with:

```
traj_2010 <- read.csv("C:/Users/stieger/Trajektorien/traj_10.csv", header=TRUE)
traj_2010$date <- as.POSIXct(strptime(traj_2010$date, format="%Y-%m-%d %H:%M", "GMT"))
traj_2010$date2 <- as.POSIXct(strptime(traj_2010$date2, format="%Y-%m-%d %H:%M", "GMT"))
```

Thus, I have trajectory data in form of:

```
head(traj_2010)
  receptor year month day hour hour.inc    lat    lon height pressure               date2       date
1        1   10     1   1    0        0 51.330 12.420  500.0    912.2 2010-01-01 00:00:00 2010-01-01
2        1    9    12  31   23       -1 51.350 12.523  464.1    915.2 2009-12-31 23:00:00 2010-01-01
3        1    9    12  31   22       -2 51.353 12.668  422.2    919.4 2009-12-31 22:00:00 2010-01-01
4        1    9    12  31   21       -3 51.329 12.840  380.9    922.0 2009-12-31 21:00:00 2010-01-01
5        1    9    12  31   20       -4 51.279 13.029  351.5    923.6 2009-12-31 20:00:00 2010-01-01
6        1    9    12  31   19       -5 51.218 13.240  335.1    924.2 2009-12-31 19:00:00 2010-01-01

```
I now use the command trajCluster:

```
cluster_2010<-trajCluster(traj_2010, method = "Angle", n.cluster = 5, col = c("red2", "blue", "green3", "purple", "black"), 
                         map.fill= FALSE, key=FALSE, main="2010", xlab="latitude", ylab="longitude", xlim=range(-35:35), ylim=range(35:70),
                         par.settings=list(axis.line=list(lwd=1.5), strip.border=list(lwd=2),
                                           fontsize=list(text=32)))
```

it runs some minutes but with the result:

==============================================================================|100% ~0 s remaining     **Error in summarise_impl(.data, dots) : 
  Evaluation error: argument "x" is missing, with no default.**

I am a little bit confused because in the past it worked without problems. Could somebody help me?

I am using the following packages:

```
library(openair)
library(plyr)
library(reshape2)
library(mapdata)
library(rworldmap)
```

**Comment by davidcarslaw** [comment] 2018-05-31 07:13
Thanks. I will check this. Could you email me the data used for the analysis please?

**Comment by itsabreg** [comment] 2018-05-31 07:17
Hi,

thanks for the fast response. As I want to calculate the Cluster of 2010 this dataset and the file is really huge. Should I send you an excerpt?

Best regards

Von: David Carslaw [mailto:notifications@github.com]
Gesendet: 31 May 2018 09:14
An: davidcarslaw/openair <openair@noreply.github.com>
Cc: Bastian Stieger <stieger@tropos.de>; Author <author@noreply.github.com>
Betreff: Re: [davidcarslaw/openair] “argument ”x“ is missing, with no default” in openair package (#152)


Thanks. I will check this. Could you email me the data used for the analysis please?

**Comment by davidcarslaw** [comment] 2018-05-31 07:28
No problem. I just tried on a simpler data set and can confirm the problem
you see. I will try and fix this later today...

David

**Comment by itsabreg** [comment] 2018-05-31 07:30
Here is an excerpt. The same error occurs.

Best regards

Von: David Carslaw [mailto:notifications@github.com]
Gesendet: 31 May 2018 09:29
An: davidcarslaw/openair <openair@noreply.github.com>
Cc: Bastian Stieger <stieger@tropos.de>; Author <author@noreply.github.com>
Betreff: Re: [davidcarslaw/openair] “argument ”x“ is missing, with no default” in openair package (#152)

No problem. I just tried on a simpler data set and can confirm the problem
you see. I will try and fix this later today...

David

**Comment by davidcarslaw** [comment] 2018-05-31 17:04
I think this is a bug in dplyr. I am still investigating but have made a small change that should get this function working; please try revised GitHub version...

**Comment by davidcarslaw** [comment] 2018-06-01 07:48
You can install the development version from GitHub. First install the package `devtools` (and load it) and then type:

`install_github("davidcarslaw/openair")`

That should give you access to the new version.

**Comment by itsabreg** [comment] 2018-06-01 08:01
Yes, it could install the new version. But I have still the same error: 

```
Error in summarise_impl(.data, dots) : 
  Evaluation error: argument "x" is missing, with no default.
```

**Comment by itsabreg** [comment] 2018-06-01 08:59
Now, I tried to calculate trajCluster and trajLevel on another computer without the changes you gave (v1.8-2 against the new v2.4-2) and the same code. For trajCluster the following error occurs:

```
> png("cluster_2010.tif", width = 10 * 300, height = 10 * 300, res = 300)
> cluster_2010=trajCluster(traj_2010, method = "Angle", n.cluster = 5, col = c("red2", "blue", "green3", "purple", "black"), 
+                          map.fill= FALSE, key=FALSE, main="2010", xlab="latitude", ylab="longitude", xlim=range(-35:35), ylim=range(35:70),
+                          par.settings=list(axis.line=list(lwd=1.5), strip.border=list(lwd=2),
+                                            fontsize=list(text=32)))
Error: could not find function "UQS"
Called from: mutate_impl(.data, dots)
Browse[1]> dev.off()
RStudioGD 
        2 
```

trajLevel works fine.

**Comment by ddlddl58** [comment] 2018-06-14 23:55
hi david,

  I also meet this problem, then i google it, most saying dplyr packages bugs. I think openair is unfit with the latest version of dplyr.Looking forward to your solution!

Best regards！

**Comment by Homaghasemi** [comment] 2018-06-22 15:54
Hi, 
I have the same problem. I am using trajLevel and PSCF. 

the error is : 
Error in summarise_impl(.data, dots) : 
  Evaluation error: argument "x" is missing, with no default.

Best, 
Homa

**Comment by masabhathini** [comment] 2018-06-22 18:12
Hi,
Here, You have loaded the csv file in to traj_2010.
and created $date2, $date.

After this, you checked only head(traj_2010). 
You need to check tail(traj_2010) and try to plot timePlot(traj_2010,pollutant="pressure").

If everything look good. Then, you proceed for the next.

My advise may helpful for you and others also.
:)

regards,
Sateesh

**Comment by ddlddl58** [comment] 2018-06-24 01:41
Hi,Sateesh

   Thank you for your kindly help!
   It solves the problem!
   
Regards!

**Comment by joshkraft** [comment] 2018-07-20 18:30
Any update on this? I am dealing with the same issue. My project ends in 1 week so I am trying to determine if I should stick with trajCluster or try another analysis method. Thanks in advance!

**Comment by davidcarslaw** [comment] 2018-07-20 19:23
This should be fixed in the github version. The problem seems to be associated with a bug in dplyr. Can you try installing the github version and try again? If you still have a problem can you provide a reproducible example and I will fix any openair issue promptly.

**Comment by Catalyst82** [comment] 2018-08-02 17:00
@davidcarslaw Please, I am also facing this problem and I need it for my research urgently. How do I install the github version? I am running out of time, please help me out. Thanks.

**Comment by davidcarslaw** [comment] 2018-08-02 17:05
I have put the binary packages [here](https://www.dropbox.com/sh/x8mmf5d54wfo5vq/AACpKqsrPkTC0guiu5ftiKNna?dl=0), which includes the zip file for Windows. If using RStudio, in a fresh R session you can install from the zip file saved somewhere on your computer. That is probably easiest.

**Closed** 2023-02-06 12:33 UTC
